service: test-suite-execution-job
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: production
  region: eu-central-1
  timeout: 120
  memorySize: 128
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - "schedule:ListSchedules"
            - "schedule:GetSchedule"
            - "schedule:CreateSchedule"
            - "schedule:UpdateSchedule"
            - "schedule:DeleteSchedule"
            - "scheduler:ListScheduleGroups"
            - "scheduler:GetScheduleGroup"
            - "scheduler:CreateScheduleGroup"
            - "scheduler:DeleteScheduleGroup"
            - "scheduler:ListTagsForResource"
            - "scheduler:TagResource"
            - "scheduler:UntagResource"
          Resource: '*'
functions:
  app:
    handler: dist/lambda.handler