service: test-suite-execution-job
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: production
  region: eu-central-1
  timeout: 400
  memorySize: 128
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - "sqs:ReceiveMessage"
            - "sqs:DeleteMessage"
            - "sqs:GetQueueAttributes"
          Resource: '*'
functions:
  app:
    handler: dist/lambda.handler